lib: [
  "_build/install/default/lib/oparser/META"
  "_build/install/default/lib/oparser/ast.ml"
  "_build/install/default/lib/oparser/dune-package"
  "_build/install/default/lib/oparser/lexer.ml"
  "_build/install/default/lib/oparser/opam"
  "_build/install/default/lib/oparser/oparser.a"
  "_build/install/default/lib/oparser/oparser.cma"
  "_build/install/default/lib/oparser/oparser.cmi"
  "_build/install/default/lib/oparser/oparser.cmt"
  "_build/install/default/lib/oparser/oparser.cmx"
  "_build/install/default/lib/oparser/oparser.cmxa"
  "_build/install/default/lib/oparser/oparser.ml"
  "_build/install/default/lib/oparser/oparser__Ast.cmi"
  "_build/install/default/lib/oparser/oparser__Ast.cmt"
  "_build/install/default/lib/oparser/oparser__Ast.cmx"
  "_build/install/default/lib/oparser/oparser__Lexer.cmi"
  "_build/install/default/lib/oparser/oparser__Lexer.cmt"
  "_build/install/default/lib/oparser/oparser__Lexer.cmx"
  "_build/install/default/lib/oparser/oparser__Parser.cmi"
  "_build/install/default/lib/oparser/oparser__Parser.cmt"
  "_build/install/default/lib/oparser/oparser__Parser.cmti"
  "_build/install/default/lib/oparser/oparser__Parser.cmx"
  "_build/install/default/lib/oparser/parser.ml"
  "_build/install/default/lib/oparser/parser.mli"
]
libexec: [
  "_build/install/default/lib/oparser/oparser.cmxs"
]
doc: [
  "_build/install/default/doc/oparser/README.md"
]
